-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 13:09:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mediviaProfile
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mediviaProfile` ;

-- -----------------------------------------------------
-- Schema mediviaProfile
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mediviaProfile` DEFAULT CHARACTER SET utf8 ;
USE `mediviaProfile` ;

-- -----------------------------------------------------
-- Table `mediviaProfile`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediviaProfile`.`countries` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `flagImage` VARCHAR(50) NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediviaProfile`.`vocations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediviaProfile`.`vocations` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediviaProfile`.`worlds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediviaProfile`.`worlds` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediviaProfile`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediviaProfile`.`users` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `comment` VARCHAR(150) NOT NULL DEFAULT 'Nothing commented.',
  `comment_owner` VARCHAR(40) NOT NULL DEFAULT 'Nobody',
  `avatar_image` VARCHAR(20) NOT NULL DEFAULT 'default',
  `vocation_uid` INT NOT NULL DEFAULT 1,
  `world_uid` INT NOT NULL DEFAULT 1,
  `country_uid` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `users_country_uid_idx` (`country_uid` ASC),
  INDEX `users_vocation_uid_idx` (`vocation_uid` ASC),
  INDEX `users_world_uid_idx` (`world_uid` ASC),
  CONSTRAINT `users_country_uid`
    FOREIGN KEY (`country_uid`)
    REFERENCES `mediviaProfile`.`countries` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_vocation_uid`
    FOREIGN KEY (`vocation_uid`)
    REFERENCES `mediviaProfile`.`vocations` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_world_uid`
    FOREIGN KEY (`world_uid`)
    REFERENCES `mediviaProfile`.`worlds` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mediviaProfile`.`countries`
-- -----------------------------------------------------
START TRANSACTION;
USE `mediviaProfile`;
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (1, 'Not Defined', 'not_defined');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (2, 'Brazil', 'brazil');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (3, 'Japan', 'japan');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mediviaProfile`.`vocations`
-- -----------------------------------------------------
START TRANSACTION;
USE `mediviaProfile`;
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `name`) VALUES (1, 'Not Defined');
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `name`) VALUES (2, 'Rookslayer');
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `name`) VALUES (3, 'Sorcerer');
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `name`) VALUES (4, 'Druid');
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `name`) VALUES (5, 'Paladin');
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `name`) VALUES (6, 'Knight');
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `name`) VALUES (7, 'Master Sorcerer');
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `name`) VALUES (8, 'Elder Druid');
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `name`) VALUES (9, 'Royal Paladin');
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `name`) VALUES (10, 'Elite Knight');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mediviaProfile`.`worlds`
-- -----------------------------------------------------
START TRANSACTION;
USE `mediviaProfile`;
INSERT INTO `mediviaProfile`.`worlds` (`uid`, `name`) VALUES (1, 'Not Defined');
INSERT INTO `mediviaProfile`.`worlds` (`uid`, `name`) VALUES (2, 'Spectrum');
INSERT INTO `mediviaProfile`.`worlds` (`uid`, `name`) VALUES (3, 'Destiny');
INSERT INTO `mediviaProfile`.`worlds` (`uid`, `name`) VALUES (4, 'Legacy');
INSERT INTO `mediviaProfile`.`worlds` (`uid`, `name`) VALUES (5, 'Pendulum');

COMMIT;

