-- MySQL Script generated by MySQL Workbench
-- Thu Oct 26 14:14:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mediviaProfile
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mediviaProfile` ;

-- -----------------------------------------------------
-- Schema mediviaProfile
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mediviaProfile` DEFAULT CHARACTER SET utf8 ;
USE `mediviaProfile` ;

-- -----------------------------------------------------
-- Table `mediviaProfile`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediviaProfile`.`countries` ;

CREATE TABLE IF NOT EXISTS `mediviaProfile`.`countries` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `flagImage` VARCHAR(50) NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediviaProfile`.`vocations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediviaProfile`.`vocations` ;

CREATE TABLE IF NOT EXISTS `mediviaProfile`.`vocations` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `manaGain` INT NOT NULL,
  `hpGain` INT NOT NULL,
  `capGain` INT NOT NULL,
  `manaRegen` DOUBLE NOT NULL,
  `hpRegen` DOUBLE NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediviaProfile`.`worlds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediviaProfile`.`worlds` ;

CREATE TABLE IF NOT EXISTS `mediviaProfile`.`worlds` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `location` VARCHAR(20) NOT NULL,
  `expRate` INT NOT NULL,
  `skillsRate` INT NOT NULL,
  `manaRate` INT NOT NULL,
  `hpRate` INT NOT NULL,
  `magicRate` INT NOT NULL,
  `lootRate` INT NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediviaProfile`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediviaProfile`.`users` ;

CREATE TABLE IF NOT EXISTS `mediviaProfile`.`users` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `comment` VARCHAR(150) NOT NULL DEFAULT 'Nothing commented.',
  `comment_owner` VARCHAR(40) NOT NULL DEFAULT 'Nobody',
  `avatar_image` VARCHAR(20) NOT NULL DEFAULT 'default',
  `vocation_uid` INT NOT NULL DEFAULT 1,
  `world_uid` INT NOT NULL DEFAULT 1,
  `country_uid` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `users_country_uid_idx` (`country_uid` ASC),
  INDEX `users_vocation_uid_idx` (`vocation_uid` ASC),
  INDEX `users_world_uid_idx` (`world_uid` ASC),
  CONSTRAINT `users_country_uid`
    FOREIGN KEY (`country_uid`)
    REFERENCES `mediviaProfile`.`countries` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_vocation_uid`
    FOREIGN KEY (`vocation_uid`)
    REFERENCES `mediviaProfile`.`vocations` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_world_uid`
    FOREIGN KEY (`world_uid`)
    REFERENCES `mediviaProfile`.`worlds` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mediviaProfile`.`countries`
-- -----------------------------------------------------
START TRANSACTION;
USE `mediviaProfile`;
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (1, 'Not Defined', 'not defined');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (2, 'Afghanistan', 'afghanistan');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (3, 'Albania', 'albania');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (4, 'Algeria', 'algeria');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (5, 'Andorra', 'andorra');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (6, 'Argentina', 'argentina');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (7, 'Armenia', 'armenia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (8, 'Australia', 'australia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (9, 'Austria', 'austria');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (10, 'Azerbaijan', 'azerbaijan');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (11, 'Bahamas', 'bahamas');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (12, 'Bahrain', 'bahrain');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (13, 'Bangladesh', 'bangladesh');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (14, 'Belarus', 'belarus');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (15, 'Belgium', 'belgium');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (16, 'Belize', 'belize');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (17, 'Benin', 'benin');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (18, 'Bolivia', 'bolivia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (19, 'Bosnia and Herzegovina', 'bosnia and herzegovina');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (20, 'Botswana', 'botswana');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (21, 'Brazil', 'brazil');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (22, 'Brunei', 'brunei');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (23, 'Bulgaria', 'bulgaria');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (24, 'Cambodia', 'cambodia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (25, 'Cameroon', 'cameroon');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (26, 'Canada', 'canada');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (27, 'Chile', 'chile');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (28, 'China', 'china');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (29, 'Colombia', 'colombia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (30, 'Congo Democratic', 'congo democratic');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (31, 'Costa Rica', 'costa rica');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (32, 'Cote Divoire', 'cote divoire');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (33, 'Croatia', 'croatia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (34, 'Cuba', 'cuba');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (35, 'Cyprus', 'cyprus');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (36, 'Czech Republic', 'czech republic');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (37, 'Denmark', 'denmark');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (38, 'Dominican Republic', 'dominican republic');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (39, 'Ecuador', 'ecuador');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (40, 'Egypt', 'egypt');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (41, 'El Salvador', 'el salvador');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (42, 'Estonia', 'estonia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (43, 'Finland', 'finland');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (44, 'France', 'france');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (45, 'Gabon', 'gabon');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (46, 'Gambia', 'gambia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (47, 'Georgia', 'georgia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (48, 'Germany', 'germany');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (49, 'Ghana', 'ghana');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (50, 'Greece', 'greece');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (51, 'Guatemala', 'guatemala');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (52, 'Guinea Bissau', 'guinea bissau');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (53, 'Haiti', 'haiti');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (54, 'Honduras', 'honduras');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (55, 'Hungary', 'hungary');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (56, 'Iceland', 'iceland');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (57, 'India', 'india');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (58, 'Indonesia', 'indonesia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (59, 'Iran', 'iran');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (60, 'Iraq', 'iraq');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (61, 'Ireland', 'ireland');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (62, 'Israel', 'israel');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (63, 'Italy', 'italy');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (64, 'Jamaica', 'jamaica');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (65, 'Japan', 'japan');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (66, 'Jordan', 'jordan');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (67, 'Kazakhstan', 'kazakhstan');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (68, 'Kenya', 'kenya');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (69, 'Kuwait', 'kuwait');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (70, 'Kyrgyzstan', 'kyrgyzstan');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (71, 'Laos', 'laos');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (72, 'Latvia', 'latvia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (73, 'Lebanon', 'lebanon');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (74, 'Liberia', 'liberia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (75, 'Libya', 'libya');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (76, 'Lithuania', 'lithuania');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (77, 'Luxemburgo', 'luxemburgo');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (78, 'Macedonia', 'macedonia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (79, 'Madagascar', 'madagascar');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (80, 'Malaysia', 'malaysia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (81, 'Mali', 'mali');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (82, 'Malta', 'malta');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (83, 'Mauritania', 'mauritania');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (84, 'Mexico', 'mexico');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (85, 'Micronesia Federated', 'micronesia federated');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (86, 'Moldova', 'moldova');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (87, 'Monaco', 'monaco');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (88, 'Mongolia', 'mongolia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (89, 'Morocco', 'morocco');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (90, 'Myanmar', 'myanmar');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (91, 'Namibia', 'namibia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (92, 'Nepal', 'nepal');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (93, 'Netherlands', 'netherlands');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (94, 'New Zealand', 'new zealand');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (95, 'Nicaragua', 'nicaragua');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (96, 'Niger', 'niger');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (97, 'Nigeria', 'nigeria');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (98, 'North Korea', 'north korea');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (99, 'Norway', 'norway');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (100, 'Oman', 'oman');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (101, 'Pakistan', 'pakistan');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (102, 'Panama', 'panama');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (103, 'Papua New Guinea', 'papua new guinea');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (104, 'Paraguay', 'paraguay');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (105, 'Peru', 'peru');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (106, 'Philippines', 'philippines');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (107, 'Poland', 'poland');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (108, 'Portugal', 'portugal');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (109, 'Qatar', 'qatar');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (110, 'Romania', 'romania');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (111, 'Russia', 'russia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (112, 'Samoa', 'samoa');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (113, 'Saudi Arabia', 'saudi arabia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (114, 'Senegal', 'senegal');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (115, 'Serbia', 'serbia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (116, 'Singapore', 'singapore');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (117, 'Slovakia', 'slovakia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (118, 'Slovenia', 'slovenia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (119, 'South Africa', 'south africa');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (120, 'South Korea', 'south korea');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (121, 'Spain', 'spain');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (122, 'Sri Lanka', 'sri lanka');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (123, 'Sweden', 'sweden');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (124, 'Switzerland', 'switzerland');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (125, 'Syria', 'syria');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (126, 'Taiwan', 'taiwan');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (127, 'Tajikistan', 'tajikistan');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (128, 'Tanzania', 'tanzania');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (129, 'Thailand', 'thailand');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (130, 'Tonga', 'tonga');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (131, 'Trinidad and Tobago', 'trinidad and tobago');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (132, 'Tunisia', 'tunisia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (133, 'Turkey', 'turkey');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (134, 'Ukraine', 'ukraine');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (135, 'United Kingdom', 'united kingdom');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (136, 'United Arab Emirates', 'united arab emirates');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (137, 'Uruguay', 'uruguay');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (138, 'Uzbekistan', 'uzbekistan');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (139, 'Vanuatu', 'vanuatu');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (140, 'Vatican City', 'vatican city');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (141, 'Venezuela', 'venezuela');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (142, 'Vietnam', 'vietnam');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (143, 'Yemen', 'yemen');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (144, 'Zambia', 'zambia');
INSERT INTO `mediviaProfile`.`countries` (`uid`, `name`, `flagImage`) VALUES (145, 'Zimbabwe', 'zimbabwe');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mediviaProfile`.`vocations`
-- -----------------------------------------------------
START TRANSACTION;
USE `mediviaProfile`;
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `class`, `name`, `manaGain`, `hpGain`, `capGain`, `manaRegen`, `hpRegen`) VALUES (1, 'No Vocation', 'Not Defined', 0, 0, 0, 0, 0);
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `class`, `name`, `manaGain`, `hpGain`, `capGain`, `manaRegen`, `hpRegen`) VALUES (2, 'No Vocation', 'No Vocation', 5, 5, 10, 0.166, 0.166);
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `class`, `name`, `manaGain`, `hpGain`, `capGain`, `manaRegen`, `hpRegen`) VALUES (3, 'Not Promoted', 'Sorcerer', 30, 5, 10, 0.333, 0.083);
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `class`, `name`, `manaGain`, `hpGain`, `capGain`, `manaRegen`, `hpRegen`) VALUES (4, 'Not Promoted', 'Druid', 30, 5, 10, 0.333, 0.083);
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `class`, `name`, `manaGain`, `hpGain`, `capGain`, `manaRegen`, `hpRegen`) VALUES (5, 'Not Promoted', 'Paladin', 15, 10, 20, 0.250, 0.125);
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `class`, `name`, `manaGain`, `hpGain`, `capGain`, `manaRegen`, `hpRegen`) VALUES (6, 'Not Promoted', 'Knight', 5, 15, 25, 0.166, 0.166);
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `class`, `name`, `manaGain`, `hpGain`, `capGain`, `manaRegen`, `hpRegen`) VALUES (7, 'Promoted', 'Master Sorcerer', 30, 5, 10, 0.500, 0.166);
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `class`, `name`, `manaGain`, `hpGain`, `capGain`, `manaRegen`, `hpRegen`) VALUES (8, 'Promoted', 'Elder Druid', 30, 5, 10, 0.500, 0.166);
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `class`, `name`, `manaGain`, `hpGain`, `capGain`, `manaRegen`, `hpRegen`) VALUES (9, 'Promoted', 'Royal Paladin', 15, 10, 20, 0.333, 0.250);
INSERT INTO `mediviaProfile`.`vocations` (`uid`, `class`, `name`, `manaGain`, `hpGain`, `capGain`, `manaRegen`, `hpRegen`) VALUES (10, 'Promoted', 'Elite Knight', 5, 15, 25, 0.166, 0.333);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mediviaProfile`.`worlds`
-- -----------------------------------------------------
START TRANSACTION;
USE `mediviaProfile`;
INSERT INTO `mediviaProfile`.`worlds` (`uid`, `name`, `location`, `expRate`, `skillsRate`, `manaRate`, `hpRate`, `magicRate`, `lootRate`) VALUES (1, 'Not Defined', 'Not Defined', 1, 1, 1, 1, 1, 1);
INSERT INTO `mediviaProfile`.`worlds` (`uid`, `name`, `location`, `expRate`, `skillsRate`, `manaRate`, `hpRate`, `magicRate`, `lootRate`) VALUES (2, 'Spectrum', 'Europe', 1, 1, 1, 1, 1, 1);
INSERT INTO `mediviaProfile`.`worlds` (`uid`, `name`, `location`, `expRate`, `skillsRate`, `manaRate`, `hpRate`, `magicRate`, `lootRate`) VALUES (3, 'Destiny', 'North America', 1, 1, 1, 1, 1, 1);
INSERT INTO `mediviaProfile`.`worlds` (`uid`, `name`, `location`, `expRate`, `skillsRate`, `manaRate`, `hpRate`, `magicRate`, `lootRate`) VALUES (4, 'Legacy', 'Europe', 2, 2, 2, 1, 1, 1);
INSERT INTO `mediviaProfile`.`worlds` (`uid`, `name`, `location`, `expRate`, `skillsRate`, `manaRate`, `hpRate`, `magicRate`, `lootRate`) VALUES (5, 'Pendulum', 'Europe', 10, 8, 4, 4, 3, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mediviaProfile`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `mediviaProfile`;
INSERT INTO `mediviaProfile`.`users` (`uid`, `username`, `email`, `password`, `comment`, `comment_owner`, `avatar_image`, `vocation_uid`, `world_uid`, `country_uid`) VALUES (1, 'Derlexy', 'jota.campagnolo@gmail.com', 'Polonia123', 'Hello guys, i\'m a RPG player.', 'Derlexy', 'derlexy', 5, 2, 19);

COMMIT;

